blank_issues_enabled: false
contact_links:
  - name: Portal oficial da TOTVS
    url: https://fundacaoeducacional132827.rm.cloudtotvs.com.br/
    about: Use o portal oficial para confirmar indisponibilidades ou divergências na fonte dos dados.
